services:
  fastapi:
    image: test:0.0.1
    container_name: fastapi_turkcell
    networks:
      - monitoring
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: 5
        loki-max-backoff: 800ms
        loki-timeout: 5s
        keep-file: "true"
        mode: "non-blocking"
    ports:
      - 80:8000
    restart: unless-stopped

networks:
  monitoring:
    external: true
